version: ~> 1.0

import:
  - silverstripe/silverstripe-travis-shared:config/provision/standard.yml

env:
  global:
    - REQUIRE_RECIPE="4.x-dev"
    # require 2.x-dev of cwp instead of ^2 (in cwp/cwp-search) for phpunit9 compatibility
    - REQUIRE_EXTRA="cwp/cwp:2.x-dev cwp/cwp-core:2.x-dev"
    - REQUIRE_CWP_STARTER_THEME=^2

# Manually defining jobs matrix instead of using standard-jobs-fixed
# to remove the postgres entry which is not compatible with cwp-search
jobs:
  fast_finish: true
  include:
    - php: 7.4
      env:
        - DB=MYSQL
        - REQUIRE_INSTALLER="$REQUIRE_RECIPE"
        - PHPUNIT_TEST=1
        - PHPCS_TEST=1
        - PHPSTAN_TEST=1
    - php: 7.4
      env:
        - DB=MYSQL
        - PDO=1
        - REQUIRE_INSTALLER="$REQUIRE_RECIPE"
        - PHPUNIT_COVERAGE_TEST=1
    - php: 8.0
      env:
        - DB=MYSQL
        - REQUIRE_INSTALLER="$REQUIRE_RECIPE"
        - PHPUNIT_TEST=1
        - REQUIRE_GRAPHQL="^3@dev || 4.x-dev"
    - php: 8.1.0
      env:
        - DB=MYSQL
        - REQUIRE_INSTALLER="$REQUIRE_RECIPE"
        - PHPUNIT_TEST=1
        - REQUIRE_GRAPHQL="^3@dev || 4.x-dev"
  allow_failures:
    - php: 8.1.0
